/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

 #ifndef _CALC_H_RPCGEN
 #define _CALC_H_RPCGEN
 
 #include <rpc/rpc.h>
 
 #ifdef __cplusplus
 extern "C" {
 #endif
 
 #define CALC_PROG 0x32222222
 #define CALC_VERS 1
 
 #if defined(__STDC__) || defined(__cplusplus)
 
 extern int * suma_1(int *, int *, CLIENT *);
 extern int * suma_1_svc(int *, int *, struct svc_req *);
 extern int * resta_1(int *, int *, CLIENT *);
 extern int * resta_1_svc(int *, int *, struct svc_req *);
 extern int * multiplica_1(int *, int *, CLIENT *);
 extern int * multiplica_1_svc(int *, int *, struct svc_req *);
 extern int * divide_1(int *, int *, CLIENT *);
 extern int * divide_1_svc(int *, int *, struct svc_req *);
 extern int calc_prog_1_freeresult(SVCXPRT *, xdrproc_t, caddr_t);
 
 #else /* K&R C */
 
 extern int * suma_1();
 extern int * suma_1_svc();
 extern int * resta_1();
 extern int * resta_1_svc();
 extern int * multiplica_1();
 extern int * multiplica_1_svc();
 extern int * divide_1();
 extern int * divide_1_svc();
 extern int calc_prog_1_freeresult();
 
 #endif /* K&R C */
 
 #ifdef __cplusplus
 }
 #endif
 
 #endif /* !_CALC_H_RPCGEN */
 